/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ojazhtukjneljfodwayq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qYXpodHVram5lbGpmb2R3YXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NDQ4NDUsImV4cCI6MjA4ODQyMDg0NX0.25L-uUTuCHjhDjvpkQBy24ccEzVb8BhQiqklYZyR-fg"